# Generated by Django 4.0.4 on 2022-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('issued', models.DateTimeField()),
                ('payed', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.IntegerField()),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'db_table': 'bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('owner', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('received', models.DateTimeField()),
            ],
            options={
                'db_table': 'license',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licenserequest',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('citizen', models.IntegerField()),
                ('form', models.CharField(max_length=500)),
                ('issued', models.DateTimeField()),
            ],
            options={
                'db_table': 'licenserequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('owner', models.IntegerField()),
                ('received', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'penalty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registerrequest',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('registration1', models.CharField(max_length=500)),
                ('registration2', models.CharField(max_length=500)),
                ('hucertificate', models.CharField(db_column='huCertificate', max_length=500)),
            ],
            options={
                'db_table': 'registerrequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('firstregistration', models.DateTimeField(db_column='firstRegistration')),
                ('displacement', models.FloatField()),
                ('fueltype', models.CharField(db_column='fuelType', max_length=45)),
                ('emissions', models.FloatField()),
                ('hudeadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
    ]
